- name: RHEL REPO Registration Play
  hosts: test
  become: true
  vars_files:
    - ../vault/secrets.yml
  vars:
    ansible_become_password: "{{ sudo_password }}"

  tasks:
    - name: Register System
      community.general.redhat_subscription:
        state: present
        username: "{{ rhel_username }}"
        password: "{{ rhel_password }}"
        auto_attach: true
